<div class="spacer"></div>
<div id="startchange"></div>
<div class="page-header">
		<h1>Terms & Conditions</h1>
</div>
<div class="container">
<div class="col-md-offset-1 col-md-10 ">
<h3 ><u>Terms of Use</u></h3><br>
<p class="text-justify"><a href="www.shilpsutra.com ">www.shilpsutra.com </a> is owned and operated by SHILPSUTRA INDIA.  a company incorporated under the laws of India. Your use of the Website and services and tools are governed by the following terms and conditions (<b>"Terms of Use"</b>) as applicable to the Website including the applicable policies which are incorporated herein by way of reference. If you transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction. By mere use of the Website, You shall be contracting with SHILPSUTRA INDIA and these terms and conditions including the policies constitute your binding obligations, with SHILPSUTRA INDIA. For the purpose of these Terms of Use, wherever the context so requires <b>"You"</b>or <b> "User"</b> shall mean any natural or legal person who has agreed to become a buyer on the Website by providing Registration Data while registering on the Website as Registered User using the computer systems. <a href="www.shilpsutra.comallows">www.shilpsutra.comallows</a>  the User to surf the Website or making purchases without registering on the Website. The term <b>"We", "Us", "Our" </b>shall mean SHILPSUTRA INDIA. When You use any of the services provided by Us through the Website, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to you. It is your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Website following the posting of changes will mean that you accept and agree to the revisions. As long as you comply with these Terms of Use, We grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.</p>
<p class="text-justify">When You use any of the services provided by Us through the Website, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to you. It is your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Website following the posting of changes will mean that you accept and agree to the revisions. As long as you comply with these Terms of Use, We grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.</p>
<p class="text-justify">ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
</p>



</div>
</div>